<section class="py-5">
    <div class="container">
        <div class="row">
            <div class="col-md-12 card">
                <div class="card-body">
                    <p class="MsoNormal"><span lang="EN-US">PLEASE READ THE FOLLOWING TERMS AND CONDITIONS OF USE CAREFULLY BEFORE USING THIS WEBSITE. </span><span style="font-size: small;"><span lang="EN-US">All users of this site agree that access to and use of this site are subject to the following terms and conditions and other applicable law. If you do not agree to these terms and conditions, please do not use this site.</span></span><span lang="EN-US" style="font-size: 12pt;"><br>
                    </span><span lang="EN-US"><br>
                    <br>
                    <strong><span style="font-family: " calibri","sans-serif";"="">Copyright</span></strong><br>
                    </span><span style="font-size: small;"><span lang="EN-US">The entire content included in this site, including but not limited to text, graphics or code is copyrighted as a collective work under the United States and other copyright laws, and is the property of www.buudl.com. The collective work includes works that are licensed to www.buudl.com. Copyright 2003, www.buudl.com ALL RIGHTS RESERVED. Permission is granted to electronically copy and print hard copy portions of this site for the sole purpose of placing an order with www.buudl.com or purchasing www.buudl.com products. You may display and, subject to any expressly stated restrictions or limitations relating to specific material, download or print portions of the material from the different areas of the site solely for your own non-commercial use, or to place an order with www.buudl.com or to purchase www.buudl.com products. Any other use, including but not limited to the reproduction, distribution, display or transmission of the content of this site is strictly prohibited, unless authorized by www.buudl.com. You further agree not to change or delete any proprietary notices from materials downloaded from the site.</span></span><span lang="EN-US" style="font-size: 12pt;"><br>
                    </span><span lang="EN-US"><br>
                    <br>
                    <strong><span style="font-family: " calibri","sans-serif";"="">Trademarks</span></strong><br>
                    </span><span style="font-size: small;"><span lang="EN-US">All trademarks, service marks and trade names of www.buudl.com used in the site are trademarks or registered trademarks of www.buudl.com</span></span><span lang="EN-US" style="font-size: 12pt;"><br>
                    </span><span lang="EN-US"><br>
                    <br>
                    <strong><span style="font-family: " calibri","sans-serif";"="">Warranty Disclaimer</span></strong><br>
                    </span><span style="font-size: small;"><span lang="EN-US">This site and the materials and products on this site are provided "as is" and without warranties of any kind, whether express or implied. To the fullest extent permissible pursuant to applicable law, www.buudl.com disclaims all warranties, express or implied, including, but not limited to, implied warranties of merchantability and fitness for a particular purpose and non-infringement. www.buudl.com does not represent or warrant that the functions contained in the site will be uninterrupted or error-free, that the defects will be corrected, or that this site or the server that makes the site available are free of viruses or other harmful components. www.buudl.com does not make any warrantees or representations regarding the use of the materials in this site in terms of their correctness, accuracy, adequacy, usefulness, timeliness, reliability or otherwise. Some states do not permit limitations or exclusions on warranties, so the above limitations may not apply to you.</span></span><span lang="EN-US" style="font-size: 12pt;"><br>
                    </span><span lang="EN-US"><br>
                    <br>
                    <strong><span style="font-family: " calibri","sans-serif";"="">Limitation of Liability</span></strong><br>
                    </span><span style="font-size: small;"><span lang="EN-US">www.buudl.com shall not be liable for any special or consequential damages that result from the use of, or the inability to use, the materials on this site or the performance of the products, even if www.buudl.com has been advised of the possibility of such damages. Applicable law may not allow the limitation of exclusion of liability or incidental or consequential damages, so the above limitation or exclusion may not apply to you.</span></span><span lang="EN-US" style="font-size: 12pt;"><br>
                    </span><span lang="EN-US"><br>
                    <br>
                    <strong><span style="font-family: " calibri","sans-serif";"="">Typographical Errors</span></strong><br>
                    </span><span style="font-size: small;"><span lang="EN-US">In the event that a www.buudl.com product is mistakenly listed at an incorrect price, www.buudl.com reserves the right to refuse or cancel any orders placed for product listed at the incorrect price. www.buudl.com reserves the right to refuse or cancel any such orders whether or not the order has been confirmed and your credit card charged. If your credit card has already been charged for the purchase and your order is cancelled, www.buudl.com shall issue a credit to your credit card account in the amount of the incorrect price.</span></span><span lang="EN-US" style="font-size: 12pt;"><br>
                    </span><span lang="EN-US"><br>
                    <br>
                    <strong><span style="font-family: " calibri","sans-serif";"="">Term; Termination</span></strong><br>
                    </span><span style="font-size: small;"><span lang="EN-US">These terms and conditions are applicable to you upon your accessing the site and/or completing the registration or shopping process. These terms and conditions, or any part of them, may be terminated by www.buudl.com without notice at any time, for any reason. The provisions relating to Copyrights, Trademark, Disclaimer, Limitation of Liability, Indemnification and Miscellaneous, shall survive any termination.</span></span><span lang="EN-US" style="font-size: 12pt;"><br>
                    </span><span lang="EN-US"><br>
                    <br>
                    <strong><span style="font-family: " calibri","sans-serif";"="">Notice</span></strong><br>
                    </span><span style="font-size: small;"><span lang="EN-US">www.buudl.com may deliver notice to you by means of e-mail, a general notice on the site, or by other reliable method to the address you have provided to www.buudl.com.</span></span><span lang="EN-US" style="font-size: 12pt;"><br>
                    </span><span lang="EN-US"><br>
                    <br>
                    <strong><span style="font-family: " calibri","sans-serif";"="">Miscellaneous</span></strong><br>
                    </span><span style="font-size: small;"><span lang="EN-US">Your use of this site shall be governed in all respects by the laws of the state of California, U.S.A., without regard to choice of law provisions, and not by the 1980 U.N. Convention on contracts for the international sale of goods. You agree that jurisdiction over and venue in any legal proceeding directly or indirectly arising out of or relating to this site (including but not limited to the purchase of www.buudl.com products) shall be in the state or federal courts located in Los Angeles County, California. Any cause of action or claim you may have with respect to the site (including but not limited to the purchase of www.buudl.com products) must be commenced within one (1) year after the claim or cause of action arises. www.buudl.com's failure to insist upon or enforce strict performance of any provision of these terms and conditions shall not be construed as a waiver of any provision or right. Neither the course of conduct between the parties nor trade practice shall act to modify any of these terms and conditions. www.buudl.com may assign its rights and duties under this Agreement to any party at any time without notice to you.</span></span><span lang="EN-US"><br>
                    <br>
                    <br>
                    <strong><span style="font-family: " calibri","sans-serif";"="">Use of Site</span></strong><br>
                    </span><span style="font-size: small;"><span lang="EN-US">Harassment in any manner or form on the site, including via e-mail, chat, or by use of obscene or abusive language, is strictly forbidden. Impersonation of others, including a www.buudl.com or other licensed employee, host, or representative, as well as other members or visitors on the site is prohibited. You may not upload to, distribute, or otherwise publish through the site any content which is libelous, defamatory, obscene, threatening, invasive of privacy or publicity rights, abusive, illegal, or otherwise objectionable which may constitute or encourage a criminal offense, violate the rights of any party or which may otherwise give rise to liability or violate any law. You may not upload commercial content on the site or use the site to solicit others to join or become members of any other commercial online service or other organization.</span></span><span lang="EN-US"><br>
                    <br>
                    <br>
                    <strong><span style="font-family: " calibri","sans-serif";"="">Participation Disclaimer</span></strong><br>
                    </span><span style="font-size: small;"><span lang="EN-US">www.buudl.com does not and cannot review all communications and materials posted to or created by users accessing the site, and is not in any manner responsible for the content of these communications and materials. You acknowledge that by providing you with the ability to view and distribute user-generated content on the site, www.buudl.com is merely acting as a passive conduit for such distribution and is not undertaking any obligation or liability relating to any contents or activities on the site. However, www.buudl.com reserves the right to block or remove communications or materials that it determines to be (a) abusive, defamatory, or obscene, (b) fraudulent, deceptive, or misleading, (c) in violation of a copyright, trademark or; other intellectual property right of another or (d) offensive or otherwise unacceptable to www.buudl.com in its sole discretion.</span></span><span lang="EN-US"><br>
                    <br>
                    <br>
                    <strong><span style="font-family: " calibri","sans-serif";"="">Indemnification</span></strong><br>
                    </span><span style="font-size: small;"><span lang="EN-US">You agree to indemnify, defend, and hold harmless www.buudl.com, its officers, directors, employees, agents, licensors and suppliers (collectively the "Service Providers") from and against all losses, expenses, damages and costs, including reasonable attorneys' fees, resulting from any violation of these terms and conditions or any activity related to your account (including negligent or wrongful conduct) by you or any other person accessing the site using your Internet account.</span></span><span lang="EN-US"><br>
                    <br>
                    <br>
                    <strong><span style="font-family: " calibri","sans-serif";"="">Third-Party Links</span></strong><br>
                    </span><span style="font-size: small;"><span lang="EN-US">In an attempt to provide increased value to our visitors, www.buudl.com may link to sites operated by third parties. However, even if the third party is affiliated with www.buudl.com, www.buudl.com has no control over these linked sites, all of which have separate privacy and data collection practices, independent of www.buudl.com. These linked sites are only for your convenience and therefore you access them at your own risk. Nonetheless, www.buudl.com seeks to protect the integrity of its web site and the links placed upon it and therefore requests any feedback on not only its own site, but for sites it links to as well (including if a specific link does not work).</span></span></p>
                </div>
            </div>
        </div>
    </div>
</section>